#!/usr/bin/env bash

NET_NAME="dockerrbaccomposed_postgres-rbac"
DNS_IP="10.0.0.72"

EPICS_DEV_DOCKER_ORG_NAME=lnls
EPICS_DEV_DOCKER_RUN_NAME=epics-dev
EPICS_DEV_DOCKER_IMAGE_NAME=docker-${EPICS_DEV_DOCKER_RUN_NAME}

MASAR_SERVICE_DOCKER_ORG_NAME=lnls
MASAR_SERVICE_DOCKER_RUN_NAME=masar-service
MASAR_SERVICE_DOCKER_IMAGE_NAME=docker-${MASAR_SERVICE_DOCKER_RUN_NAME}

MASAR_SERVICE_DOCKER_DATA_VOLUME=${MASAR_SERVICE_DOCKER_RUN_NAME}-data-volume
MASAR_SERVICE_DOCKER_CONFIG_VOLUME=${MASAR_SERVICE_DOCKER_RUN_NAME}-config-volume


MASAR_SERVICE_VERSION=master

MASAR_SERVICE_REPO=masarService
